
# This file is used to configure documentation for your project.
# Read more about various options under:
# ---> https://github.com/GEM7318/TeamDoc


# -- Overview / Table of Contents Information ---------------------------------
[core]
    title = 'Code2Markdown'  # [REQUIRED] Semantic title of document
    document-type = 'Tooling'  # [REQUIRED] (Automation / Data Infrastructure, Reporting, etc)
    contributors = ['Grant Murray']  # [REQUIRED] Contributors to project (1st is primary)
    repo-url = 'https://github.com/GEM7318/Code2Markdown'  # URL to git repository
    authored-date = '2020-09-21'  # [REQUIRED] Date Authored
    scope = ['README~teamdocs.md', 'knowledge~toc.md', 'teamdocs~wiki.md']  # Scope of documentation to generate
    scope-includes-parent-doc = true  # [REQUIRED] Include generated documentation in parent document
    languages-tools = ['python']  # Languages & tools used in project
    tags = ['markdown', 'html', 'rendering']  # Tags associated with the project (e.g. ['new customers', 'customer frequency'])
    teams = ['DS&A']  # Teams associated with the project
    short-description = 'Simple Python package to parse code files into renderable markdown.'  # Short description of project



# -- Configuration/Options ----------------------------------------------------
[options]
    alternate-toc-title = ''  # Alternative title for TOC
    generate-dir-index = true  # [REQUIRED] Generate lookup (dir-index.csv) to document directory contents
    generate-file-index = true  # [REQUIRED] Generate lookup (file-index.csv) to document file contents
    alt-root-dir = ''  # [REQUIRED] Alternate directory to consider root (default is parent of teamdocs folder)
    exclude-dirs = ['.git', '.idea', '__pycache__', '.pytest_pycache', 'projectenv', '.env', 'env', 'build', '_build', '.ipynb_checkpoints', 'teamdocs']  # Directories to exclude from file/directory indices
    mirror-project-in-teamdocs = true  # [REQUIRED] Mirror directory in user/team knowledge repository
    limit-mirrored-project-to-dir-index = true  # [REQUIRED] Only include directories containing descriptions in dir-index.csv
    persist-mirrored-project-if-source-removed = false  # [REQUIRED] Keep teamdocs source/mirror repository if user removes local/source repository
    alt-dirs-to-include-in-mirrored-project = ['']  # List of directories to include in mirrored project (if other than indicated in dir-index.csv)
    create-code-appendix = true  # [REQUIRED] Appendix syntactically highlighted renders of code files in documentation
    limit-code-appendix-to-file-index = true  # [REQUIRED] Only include renders of code files containing descriptions in files.csv
    preferred-code-types = ['.py', '.sql']  # [REQUIRED] Preferred types will be placed before others in code appendix.
    generate-dirtree = true  # [REQUIRED] Generate dirtree.md to include in documentation
    dirtree-file-limit = 15  # [REQUIRED] Max number of files to show in a directory before truncating tree output
    limit-dirtree-to-dir-index = true  # [REQUIRED] Only include directories containing descriptions in dir-index.csv



